name: OnlineNow
options:
  bundleIdPrefix: com.gdemay
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
targets:
  OnlineNow:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - App
      - Sources/OnlineNow
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: Online Now
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gdemay.onlinenow
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: "1,2"
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: MV634X2D7X
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_REQUIRED: "YES"
        CODE_SIGNING_ALLOWED: "YES"
        # App Store Distribution Settings
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: App/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: "Online Now"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        ENABLE_BITCODE: NO
        VALIDATE_PRODUCT: YES
